services:
  - type: web
    name: lib-seat-campus-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/ping
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ClientApp__AllowedOrigins
        sync: false
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: JwtSettings__Key
        generateValue: true
      - key: JwtSettings__Issuer
        value: LibraryExamAPI
      - key: JwtSettings__Audience
        value: LibraryExamClient
      - key: DefaultAdmin__Email
        sync: false
      - key: DefaultAdmin__Password
        sync: false
      - key: Smtp__Host
        sync: false
      - key: Smtp__Port
        value: "587"
      - key: Smtp__Username
        sync: false
      - key: Smtp__Password
        sync: false
      - key: Smtp__From
        sync: false
      - key: Smtp__EnableSsl
        value: "true"
