import { useExamFeature } from '../../hooks/useExamFeature';

export default function ExamSection({ active, enabled }) {
  const feature = useExamFeature(enabled);
  const { status, loading, rooms, invigilators, exams, allocations, roomForm, setRoomForm, invigilatorForm, setInvigilatorForm, examForm, setExamForm, allocationForm, setAllocationForm, overrideSeatForm, setOverrideSeatForm, editingRoomId, editingInvigilatorId, editingExamId, createRoom: onRoomSubmit, createInvigilator: onInvigilatorSubmit, createExam: onExamSubmit, allocateSeats: onAllocate, overrideSeat: onOverride, deleteRoom: onDeleteRoom, deleteInvigilator: onDeleteInvigilator, deleteExam: onDeleteExam, isSubmitting } = feature;
  const onEditRoom = (room) => { feature.setEditingRoomId(room.roomId); setRoomForm({ roomNo: room.roomNo, capacity: room.capacity, benchLayout: room.benchLayout }); };
  const onEditInvigilator = (item) => { feature.setEditingInvigilatorId(item.staffId); setInvigilatorForm({ name: item.name, dept: item.dept }); };
  const onEditExam = (exam) => { feature.setEditingExamId(exam.examId); setExamForm({ course: exam.course, semester: String(exam.semester), examDate: String(exam.examDate).slice(0, 10), timeSlot: exam.timeSlot?.slice(0, 5) || '09:00' }); };
  const onCancelRoom = () => { feature.setEditingRoomId(null); setRoomForm({ roomNo: '', capacity: 30, benchLayout: '10-per-bench' }); };
  const onCancelInvigilator = () => { feature.setEditingInvigilatorId(null); setInvigilatorForm({ name: '', dept: '' }); };
  const onCancelExam = () => { feature.setEditingExamId(null); setExamForm({ course: '', semester: '1', examDate: feature.defaultExamDate, timeSlot: '09:00' }); };
  if (!active) return null;
  const semesters = [1,2,3,4,5,6,7,8];
  return <section className="section active"><div className="section-header"><h1>Exam Management</h1><p>Manage exam schedules, rooms, and seat allocations</p></div>{status.message && <div className={`message ${status.type}`}>{status.message}</div>}{loading && <div className="loading-skeleton"><span className="skeleton-block skeleton-wide" /><span className="skeleton-block skeleton-wide" /></div>}
    {active === 'exam-rooms' && <><div className="form-card"><h2>{editingRoomId ? 'Edit room' : 'Create room'}</h2><form onSubmit={onRoomSubmit} className="form-group"><label>Room number<input value={roomForm.roomNo} onChange={(event) => setRoomForm((current) => ({ ...current, roomNo: event.target.value }))} required /></label><div className="form-row"><label>Capacity<input type="number" min="1" value={roomForm.capacity} onChange={(event) => setRoomForm((current) => ({ ...current, capacity: Number(event.target.value) }))} required /></label><label>Bench layout<input value={roomForm.benchLayout} onChange={(event) => setRoomForm((current) => ({ ...current, benchLayout: event.target.value }))} required /></label></div><div className="form-actions"><button className="btn btn-primary" disabled={isSubmitting}>{editingRoomId ? 'Save room' : 'Create room'}</button>{editingRoomId && <button type="button" className="btn btn-secondary" onClick={onCancelRoom}>Cancel</button>}</div></form></div><div className="table-container"><h2>Rooms</h2><table><thead><tr><th>Room</th><th>Capacity</th><th>Layout</th><th>Occupied</th><th>Actions</th></tr></thead><tbody>{rooms.map((room) => <tr key={room.roomId}><td>{room.roomNo}</td><td>{room.capacity}</td><td>{room.benchLayout}</td><td>{room.occupiedSeats}</td><td><div className="action-group"><button className="btn btn-secondary" onClick={() => onEditRoom(room)}>Edit</button><button className="btn btn-destructive" onClick={() => onDeleteRoom(room.roomId)}>Delete</button></div></td></tr>)}</tbody></table></div></>}
    {active === 'exam-invigilators' && <><div className="form-card"><h2>{editingInvigilatorId ? 'Edit invigilator' : 'Add invigilator'}</h2><form onSubmit={onInvigilatorSubmit} className="form-group"><label>Full name<input value={invigilatorForm.name} onChange={(event) => setInvigilatorForm((current) => ({ ...current, name: event.target.value }))} required /></label><label>Department<input value={invigilatorForm.dept} onChange={(event) => setInvigilatorForm((current) => ({ ...current, dept: event.target.value }))} required /></label><div className="form-actions"><button className="btn btn-primary" disabled={isSubmitting}>{editingInvigilatorId ? 'Save invigilator' : 'Add invigilator'}</button>{editingInvigilatorId && <button type="button" className="btn btn-secondary" onClick={onCancelInvigilator}>Cancel</button>}</div></form></div><div className="table-container"><h2>Invigilators</h2><table><thead><tr><th>Name</th><th>Department</th><th>Assigned</th><th>Actions</th></tr></thead><tbody>{invigilators.map((item) => <tr key={item.staffId}><td>{item.name}</td><td>{item.dept}</td><td>{item.assignedCount}</td><td><div className="action-group"><button className="btn btn-secondary" onClick={() => onEditInvigilator(item)}>Edit</button><button className="btn btn-destructive" onClick={() => onDeleteInvigilator(item.staffId)}>Delete</button></div></td></tr>)}</tbody></table></div></>}
    {active === 'exam-schedule' && <><div className="form-card"><h2>{editingExamId ? 'Edit exam' : 'Create exam'}</h2><form onSubmit={onExamSubmit} className="form-group"><label>Course name<input value={examForm.course} onChange={(event) => setExamForm((current) => ({ ...current, course: event.target.value }))} required /></label><div className="form-row"><label>Semester<select value={examForm.semester} onChange={(event) => setExamForm((current) => ({ ...current, semester: event.target.value }))}>{semesters.map((item) => <option key={item}>{item}</option>)}</select></label><label>Time slot<input type="time" value={examForm.timeSlot} onChange={(event) => setExamForm((current) => ({ ...current, timeSlot: event.target.value }))} required /></label></div><label>Exam date<input type="date" value={examForm.examDate} onChange={(event) => setExamForm((current) => ({ ...current, examDate: event.target.value }))} required /></label><div className="form-actions"><button className="btn btn-primary" disabled={isSubmitting}>{editingExamId ? 'Save exam' : 'Create exam'}</button>{editingExamId && <button type="button" className="btn btn-secondary" onClick={onCancelExam}>Cancel</button>}</div></form></div><div className="table-container"><h2>Exams</h2><table><thead><tr><th>Course</th><th>Semester</th><th>Date</th><th>Time</th><th>Seats</th><th>Actions</th></tr></thead><tbody>{exams.map((exam) => <tr key={exam.examId}><td>{exam.course}</td><td>{exam.semester}</td><td>{new Date(exam.examDate).toLocaleDateString()}</td><td>{exam.timeSlot}</td><td>{exam.seatCount}</td><td><div className="action-group"><button className="btn btn-secondary" onClick={() => onEditExam(exam)}>Edit</button><button className="btn btn-destructive" onClick={() => onDeleteExam(exam.examId)}>Delete</button></div></td></tr>)}</tbody></table></div></>}
    {active === 'exam-allocations' && <><div className="form-card"><h2>Allocate seats</h2><form onSubmit={onAllocate} className="form-group"><div className="form-row"><label>Exam<select value={allocationForm.examId} onChange={(event) => setAllocationForm((current) => ({ ...current, examId: event.target.value }))} required><option value="">Select exam</option>{exams.map((exam) => <option key={exam.examId} value={exam.examId}>{exam.course}</option>)}</select></label><label>Room<select value={allocationForm.roomId} onChange={(event) => setAllocationForm((current) => ({ ...current, roomId: event.target.value }))} required><option value="">Select room</option>{rooms.map((room) => <option key={room.roomId} value={room.roomId}>{room.roomNo}</option>)}</select></label></div><label>Invigilator<select value={allocationForm.invigilatorId} onChange={(event) => setAllocationForm((current) => ({ ...current, invigilatorId: event.target.value }))}><option value="">Optional</option>{invigilators.map((item) => <option key={item.staffId} value={item.staffId}>{item.name}</option>)}</select></label><button className="btn btn-primary" disabled={isSubmitting}>Generate seat plan</button></form></div><div className="form-card"><h2>Manual seat override</h2><form onSubmit={onOverride} className="form-group"><label>Seat ID<input type="number" min="1" value={overrideSeatForm.seatId} onChange={(event) => setOverrideSeatForm((current) => ({ ...current, seatId: event.target.value }))} required /></label><label>Room ID<input type="number" min="1" value={overrideSeatForm.roomId} onChange={(event) => setOverrideSeatForm((current) => ({ ...current, roomId: event.target.value }))} required /></label><div className="form-row"><label>Bench No<input type="number" min="1" value={overrideSeatForm.benchNo} onChange={(event) => setOverrideSeatForm((current) => ({ ...current, benchNo: event.target.value }))} required /></label><label>Seat No<input type="number" min="1" value={overrideSeatForm.seatNo} onChange={(event) => setOverrideSeatForm((current) => ({ ...current, seatNo: event.target.value }))} required /></label></div><button className="btn btn-primary" disabled={isSubmitting}>Override seat</button></form></div><div className="table-container"><h2>Seat allocations</h2><table><thead><tr><th>Course</th><th>Room</th><th>Student</th><th>Roll no</th><th>Bench</th><th>Seat</th></tr></thead><tbody>{allocations.map((item) => <tr key={item.seatId}><td>{item.course}</td><td>{item.roomNo}</td><td>{item.studentName}</td><td>{item.rollNo}</td><td>{item.benchNo}</td><td>{item.seatNo}</td></tr>)}</tbody></table></div></>}
  </section>;
}
