import LoadingSkeleton from '../feedback/LoadingSkeleton';
import { useLibraryFeature } from '../../hooks/useLibraryFeature';

const emptyBook = { title: '', author: '', isbn: '', genre: 'Technology', copiesAvailable: 1, coverImageUrl: '', description: '', publisher: '', publishedYear: new Date().getFullYear() };

export default function LibrarySection({ active, enabled }) {
  const feature = useLibraryFeature(enabled);
  const { status, loading, reports, books, members, issues, search, genre, setSearch: onSearch, setGenre: onGenre, reload: onRefresh, libraryForm: bookForm, setLibraryForm: setBookForm, editingBookId, setEditingBookId, saveBook: onBookSubmit, deleteBook: onDeleteBook, issueForm, setIssueForm, issueBook: onIssue, returnBook: onReturn, bookDetails, loadBookDetails: onBookDetails, commentText, setCommentText, addComment: onComment, reactionType, addReaction: onReaction, isSubmitting } = feature;
  const onEditBook = (book) => { setEditingBookId(book.bookId); setBookForm({ title: book.title, author: book.author, isbn: book.isbn, genre: book.genre, copiesAvailable: book.copiesAvailable, coverImageUrl: book.coverImageUrl || '', description: book.description || '', publisher: book.publisher || '', publishedYear: book.publishedYear || new Date().getFullYear() }); };
  if (!active) return null;
  const resetBook = () => { setEditingBookId(null); setBookForm(emptyBook); };
  return <section className="section active">
    <div className="section-header"><h1>Library Management</h1><p>Manage books, issues, and library resources</p></div>
    {status.message && <div className={`message ${status.type}`}>{status.message}</div>}
    {loading && <LoadingSkeleton variant="rows" />}
    {reports && <div className="stats-grid"><div className="stat-card"><span>Total books</span><strong>{reports.totalBooks ?? books.length}</strong></div><div className="stat-card"><span>Available copies</span><strong>{reports.totalAvailableCopies ?? books.reduce((sum, book) => sum + (book.copiesAvailable || 0), 0)}</strong></div><div className="stat-card"><span>Active issues</span><strong>{reports.activeIssueCount ?? issues.filter((issue) => issue.returnDate === null).length}</strong></div><div className="stat-card"><span>Overdue</span><strong>{reports.overdueCount ?? issues.filter((issue) => issue.returnDate === null && issue.isOverdue).length}</strong></div></div>}
    {active === 'library-books' && <>
      <div className="form-card"><h2>{editingBookId ? 'Edit book' : 'Add new book'}</h2><form onSubmit={onBookSubmit} className="form-group">
        <label>Title<input value={bookForm.title} onChange={(event) => setBookForm((current) => ({ ...current, title: event.target.value }))} required /></label>
        <div className="form-row"><label>Author<input value={bookForm.author} onChange={(event) => setBookForm((current) => ({ ...current, author: event.target.value }))} required /></label><label>ISBN<input value={bookForm.isbn} onChange={(event) => setBookForm((current) => ({ ...current, isbn: event.target.value }))} required /></label></div>
        <div className="form-row"><label>Genre<input value={bookForm.genre} onChange={(event) => setBookForm((current) => ({ ...current, genre: event.target.value }))} required /></label><label>Copies<input type="number" min="1" value={bookForm.copiesAvailable} onChange={(event) => setBookForm((current) => ({ ...current, copiesAvailable: Number(event.target.value) }))} required /></label></div>
        <label>Cover URL<input value={bookForm.coverImageUrl} onChange={(event) => setBookForm((current) => ({ ...current, coverImageUrl: event.target.value }))} /></label><label>Publisher<input value={bookForm.publisher} onChange={(event) => setBookForm((current) => ({ ...current, publisher: event.target.value }))} /></label>
        <div className="form-row"><label>Published year<input type="number" value={bookForm.publishedYear} onChange={(event) => setBookForm((current) => ({ ...current, publishedYear: Number(event.target.value) }))} /></label><label>Description<input value={bookForm.description} onChange={(event) => setBookForm((current) => ({ ...current, description: event.target.value }))} /></label></div>
        <div className="form-actions"><button type="submit" className="btn btn-primary" disabled={isSubmitting}>{isSubmitting ? 'Saving...' : editingBookId ? 'Save book' : 'Add book'}</button>{editingBookId && <button type="button" className="btn btn-secondary" onClick={resetBook}>Cancel</button>}</div>
      </form></div>
      <div className="table-container"><div className="table-header"><h2>Book catalog</h2><div className="table-toolbar"><input value={search} onChange={(event) => onSearch(event.target.value)} placeholder="Search books" /><select value={genre} onChange={(event) => onGenre(event.target.value)}><option value="all">All genres</option>{Array.from(new Set(books.map((book) => book.genre))).filter(Boolean).map((item) => <option key={item} value={item}>{item}</option>)}</select><button type="button" className="btn btn-secondary" onClick={onRefresh}>Refresh</button></div></div><table><thead><tr><th>Title</th><th>Author</th><th>ISBN</th><th>Genre</th><th>Copies</th><th>Actions</th></tr></thead><tbody>{books.map((book) => <tr key={book.bookId}><td>{book.title}</td><td>{book.author}</td><td>{book.isbn}</td><td>{book.genre}</td><td>{book.copiesAvailable}</td><td><div className="action-group"><button type="button" className="btn btn-secondary" onClick={() => onBookDetails(book.bookId)}>View</button><button type="button" className="btn btn-secondary" onClick={() => onEditBook(book)}>Edit</button><button type="button" className="btn btn-destructive" onClick={() => onDeleteBook(book.bookId)}>Delete</button></div></td></tr>)}</tbody></table></div>
      {bookDetails && <div className="card"><div className="card-header"><h3>{bookDetails.title}</h3></div><div className="card-body"><div className="profile-card"><div><label>Author</label><strong>{bookDetails.author}</strong></div><div><label>ISBN</label><strong>{bookDetails.isbn}</strong></div><div><label>Genre</label><strong>{bookDetails.genre}</strong></div><div><label>Copies</label><strong>{bookDetails.copiesAvailable}</strong></div></div><div className="action-group"><button type="button" className={`btn btn-secondary ${reactionType === 'like' ? 'active' : ''}`} onClick={() => onReaction('like')}>Like ({bookDetails.reactions?.likes ?? 0})</button><button type="button" className={`btn btn-secondary ${reactionType === 'dislike' ? 'active' : ''}`} onClick={() => onReaction('dislike')}>Dislike ({bookDetails.reactions?.dislikes ?? 0})</button></div><form onSubmit={onComment} className="auth-form"><label>Add comment<textarea value={commentText} onChange={(event) => setCommentText(event.target.value)} rows="3" placeholder="Share your feedback on this book" /></label><button type="submit" className="btn btn-primary" disabled={isSubmitting}>Post comment</button></form>{bookDetails.comments?.map((comment) => <div key={comment.commentId} style={{ padding: '1rem', borderBottom: '1px solid var(--border)' }}><strong>{comment.studentName}</strong><span style={{ color: 'var(--muted-foreground)' }}> - {new Date(comment.createdAt).toLocaleDateString()}</span><p>{comment.commentText}</p></div>)}</div></div>}
    </>}
    {active === 'library-issues' && <><div className="form-card"><h2>Issue a book</h2><form onSubmit={onIssue} className="form-group"><label>Book<select value={issueForm.bookId} onChange={(event) => setIssueForm((current) => ({ ...current, bookId: event.target.value }))} required><option value="">Select a book</option>{books.filter((book) => book.copiesAvailable > 0).map((book) => <option key={book.bookId} value={book.bookId}>{book.title} ({book.copiesAvailable} available)</option>)}</select></label><label>Student<select value={issueForm.studentId} onChange={(event) => setIssueForm((current) => ({ ...current, studentId: event.target.value }))} required><option value="">Select a student</option>{members.filter((member) => member.role === 'Student').map((member) => <option key={member.studentId} value={member.studentId}>{member.name} ({member.rollNo || `Student #${member.studentId}`})</option>)}</select></label><label>Due days<input type="number" min="1" max="90" value={issueForm.dueDays} onChange={(event) => setIssueForm((current) => ({ ...current, dueDays: event.target.value }))} /></label><button type="submit" className="btn btn-primary" disabled={isSubmitting}>{isSubmitting ? 'Issuing...' : 'Issue book'}</button></form></div><div className="table-container"><div className="table-header"><h2>Issue ledger</h2></div><table><thead><tr><th>Student</th><th>Book</th><th>Issue date</th><th>Due date</th><th>Fine</th><th>Action</th></tr></thead><tbody>{issues.map((issue) => <tr key={issue.issueId}><td>{issue.studentName}</td><td>{issue.bookTitle}</td><td>{new Date(issue.issueDate).toLocaleDateString()}</td><td>{new Date(issue.dueDate).toLocaleDateString()}</td><td>${issue.fineAmount ?? 0}</td><td>{!issue.returnDate && <button type="button" className="btn btn-secondary" onClick={() => onReturn(issue.issueId)}>Return</button>}</td></tr>)}</tbody></table></div></>}
  </section>;
}
